services:
  - type: web
    name: WinZoneVipBot3
    env: python
    plan: free
    region: oregon

    # Versão estável e compatível
    pythonVersion: 3.10.12

    buildCommand: pip install -r requirements.txt

    startCommand: python winzone_bot_manualpix.py

    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: CHANNEL_ID
        sync: false
      - key: OWNER_ID
        sync: false
      - key: PIX_KEY
        sync: false
      - key: PYTHON_VERSION
        value: 3.10.12

    autoDeploy: true
